[package]
name = "folio-ide"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
folio-analysis = { path = "../../compiler/analysis" }
folio-format-declarations = { path = "../../formats/declarations" }
folio-diagnostics = { path = "../../foundation/diagnostics" }
folio-build = { path = "../../project/build" }
folio-hir = { path = "../../compiler/hir" }
folio-papyrus = { path = "../../languages/papyrus" }
folio-source = { path = "../../foundation/source" }
folio-profiles = { path = "../../foundation/profiles" }
tracing.workspace = true
