[package]
name = "folio-lowering"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
folio-hir = { path = "../hir" }
folio-mir = { path = "../mir" }
folio-profiles = { path = "../../foundation/profiles" }
folio-diagnostics = { path = "../../foundation/diagnostics" }
folio-source = { path = "../../foundation/source" }
tracing.workspace = true
